//Command line interface
use clap::{App, AppSettings, Arg, SubCommand};

const DH: &str = "Daniel Herslöf <d_herslof@hotmail.com>";

pub fn create_cli_options() -> App<'static, 'static> {
    App::new(crate_name!())
      .version(crate_version!())
      .author(DH)
      .about(crate_description!())
      .setting(AppSettings::InferSubcommands)
      .subcommand(SubCommand::with_name("print")
         .author(DH)
         .about("Prints file permissions")
         .arg(Arg::with_name("file_name")
            .help("File name or directory")
            .takes_value(true)
            .index(1)
            .required(true))
         .setting(AppSettings::InferSubcommands)
         .subcommand(SubCommand::with_name("simple")
            .about("Prints file permissions in pretty table - Default print style")
            .arg(Arg::with_name("user")
               .help("Prints user permissions")
               .takes_value(false)
               .short("u")
               .long("user")
               .required(false)
            )
            .arg(Arg::with_name("group")
               .help("Prints group permissions")
               .takes_value(false)
               .short("g")
               .long("group")
               .required(false)
            )
            .arg(Arg::with_name("other")
               .help("Prints other permissions")
               .takes_value(false)
               .short("o")
               .long("other")
               .required(false)
            )
         )

         .setting(AppSettings::InferSubcommands)
         .subcommand(SubCommand::with_name("unix")
            .about("Prints file permissions in unix style")
            .arg(Arg::with_name("user")
               .help("Prints user permissions")
               .takes_value(false)
               .short("u")
               .long("user")
               .required(false)
            )
            .arg(Arg::with_name("group")
               .help("Prints group permissions")
               .takes_value(false)
               .short("g")
               .long("group")
               .required(false)
            )
            .arg(Arg::with_name("other")
               .help("Prints other permissions")
               .takes_value(false)
               .short("o")
               .long("other")
               .required(false)
            )
         )
         .setting(AppSettings::InferSubcommands)
         .subcommand(SubCommand::with_name("number")
            .about("Print the number representation of the file permissions"))
   )
      .subcommand(SubCommand::with_name("calculate")
         .author(DH)
         .about("Calculate number representation of file permissions provided\nFormat: 'rwe' for setting all permission bits\nNote: Sticky bit will be ignored")
         .arg(Arg::with_name("user")
            .help("User permissions")
            .takes_value(true)
            .short("u")
            .long("user"))
         .arg(Arg::with_name("group")
            .help("Group permissions")
            .takes_value(true)
            .short("g")
            .long("group"))
         .arg(Arg::with_name("other")
         .help("Other permissions")
         .takes_value(true)
         .short("o")
         .long("other"))
      )
}
